version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: myhouse_postgres
    environment:
      POSTGRES_DB: myhouse_dev
      POSTGRES_USER: myhouse_user
      POSTGRES_PASSWORD: myhouse_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./frontend/src/lib/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myhouse_user -d myhouse_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
